export enum ActionsEnum {
  LOAD_COURSES_REQUEST = 'feed:LOAD_COURSES_REQUEST',
  LOAD_COURSES_SUCCESS = 'feed:LOAD_COURSES_SUCCESS',
  LOAD_COURSES_FAILURE = 'feed:LOAD_COURSES_FAILURE',
  LOAD_COURSE_REQUEST = 'feed:LOAD_COURSE_REQUEST',
  LOAD_COURSE_SUCCESS = 'feed:LOAD_COURSE_SUCCESS',
  LOAD_COURSE_FAILURE = 'feed:LOAD_COURSE_FAILURE',
}


