export enum ActionsEnum {
  LOAD_COURSES_REQUEST = 'course:LOAD_COURSES_REQUEST',
  LOAD_COURSES_SUCCESS = 'course:LOAD_COURSES_SUCCESS',
  LOAD_COURSES_FAILURE = 'course:LOAD_COURSES_FAILURE',
  LOAD_COURSE_REQUEST = 'course:LOAD_COURSE_REQUEST',
  LOAD_COURSE_SUCCESS = 'course:LOAD_COURSE_SUCCESS',
  LOAD_COURSE_FAILURE = 'course:LOAD_COURSE_FAILURE',
  FILTER_COURSES = 'course:FILTER_COURSES',
}


